<?php

$var = array(
    'guard' => 'admin',
    'fillable' => array(0 => 'name', 1 => 'email', 2 => 'password',),
    'hidden' => array(0 => 'password', 1 => 'remember_token',),
    'connection' => 'mysql',
    'table' => NULL,
    'primaryKey' => 'id',
    'keyType' => 'int',
    'incrementing' => true,
    'with' => array(),
    'withCount' => array(),
    'perPage' => 15,
    'exists' => true,
    'wasRecentlyCreated' => false,
    'attributes' => array('id' => 1, 'name' => 'admin', 'email' => 'phamque.adnetplus@gmail.com', 'password' => '$2y$10$SBN7yt4PcyhtphNYvctInuLqWYQjwva6e13GvOpe7gyQut0w2L0Ju', 'remember_token' => 'M6D88e8dTa4AgvZxPzi4LVvSoEJ6X4zdAGriczPpDQkXNkCuUYE5qDHKHiac', 'created_at' => '2018-05-03 03:39:51', 'updated_at' => '2018-05-03 10:41:30',),
    'original' => array('id' => 1, 'name' => 'admin', 'email' => 'phamque.adnetplus@gmail.com', 'password' => '$2y$10$SBN7yt4PcyhtphNYvctInuLqWYQjwva6e13GvOpe7gyQut0w2L0Ju', 'remember_token' => 'M6D88e8dTa4AgvZxPzi4LVvSoEJ6X4zdAGriczPpDQkXNkCuUYE5qDHKHiac', 'created_at' => '2018-05-03 03:39:51', 'updated_at' => '2018-05-03 10:41:30',),
    'casts' => array(),
    'dates' => array(),
    'dateFormat' => NULL,
    'appends' => array(),
    'events' => array(),
    'observables' => array(),
    'relations' => array(),
    'touches' => array(),
    'timestamps' => true,
    'visible' => array(),
    'guarded' => array(0 => '*',),
    'rememberTokenName' => 'remember_token',
    );


$varr = array('fillable' => array(0 => 'name', 1 => 'email', 2 => 'password',),
    'hidden' => array(0 => 'password', 1 => 'remember_token',),
    'connection' => 'mysql',
    'table' => NULL,
    'primaryKey' => 'id',
    'keyType' => 'int',
    'incrementing' => true,
    'with' => array(),
    'withCount' => array(),
    'perPage' => 15,
    'exists' => true,
    'wasRecentlyCreated' => false,
    'attributes' => array('id' => 1, 'name' => 'user', 'email' => 'phamque.adnetplus@gmail.com', 'password' => '$2y$10$s1BR03Pod7FcMxXg6FXYe.CiNMMDIMB5Cl0lNLW/5wRCxOfZshv4y', 'remember_token' => 'gpPQzcDYkqxMm3cBPQbi3ToRTSbLgbSVAwKu76oSRSWnTTgBSyuV88EHiEvC', 'created_at' => '2018-05-02 21:32:21', 'updated_at' => '2018-05-03 09:39:11',),
    'original' => array('id' => 1, 'name' => 'user', 'email' => 'phamque.adnetplus@gmail.com', 'password' => '$2y$10$s1BR03Pod7FcMxXg6FXYe.CiNMMDIMB5Cl0lNLW/5wRCxOfZshv4y', 'remember_token' => 'gpPQzcDYkqxMm3cBPQbi3ToRTSbLgbSVAwKu76oSRSWnTTgBSyuV88EHiEvC', 'created_at' => '2018-05-02 21:32:21', 'updated_at' => '2018-05-03 09:39:11',),
    'casts' => array(),
    'dates' => array(),
    'dateFormat' => NULL,
    'appends' => array(),
    'events' => array(),
    'observables' => array(),
    'relations' => array(),
    'touches' => array(),
    'timestamps' => true,
    'visible' => array(),
    'guarded' => array(0 => '*',),
    'rememberTokenName' => 'remember_token',);
